#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAUtil.Controllers
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ChmPortal")]
	public partial class ModulesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMODULE(MODULE instance);
    partial void UpdateMODULE(MODULE instance);
    partial void DeleteMODULE(MODULE instance);
    partial void InsertCHURCH_MODULE(CHURCH_MODULE instance);
    partial void UpdateCHURCH_MODULE(CHURCH_MODULE instance);
    partial void DeleteCHURCH_MODULE(CHURCH_MODULE instance);
    #endregion
		
		public ModulesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ChmPortalConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModulesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModulesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModulesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModulesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MODULE> MODULEs
		{
			get
			{
				return this.GetTable<MODULE>();
			}
		}
		
		public System.Data.Linq.Table<CHURCH_MODULE> CHURCH_MODULEs
		{
			get
			{
				return this.GetTable<CHURCH_MODULE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ChmPortal.dbo.MODULE")]
	public partial class MODULE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MODULE_ID;
		
		private string _MODULE_NAME;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private System.Nullable<int> _CREATED_BY_USER_ID;
		
		private System.Nullable<System.DateTime> _LAST_UPDATED_DATE;
		
		private System.Nullable<int> _LAST_UPDATED_BY_USER_ID;
		
		private string _CREATED_BY_LOGIN;
		
		private string _LAST_UPDATED_BY_LOGIN;
		
		private System.Nullable<int> _OLD_MODULE_ID;
		
		private EntitySet<CHURCH_MODULE> _CHURCH_MODULEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMODULE_IDChanging(int value);
    partial void OnMODULE_IDChanged();
    partial void OnMODULE_NAMEChanging(string value);
    partial void OnMODULE_NAMEChanged();
    partial void OnCREATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATED_DATEChanged();
    partial void OnCREATED_BY_USER_IDChanging(System.Nullable<int> value);
    partial void OnCREATED_BY_USER_IDChanged();
    partial void OnLAST_UPDATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnLAST_UPDATED_DATEChanged();
    partial void OnLAST_UPDATED_BY_USER_IDChanging(System.Nullable<int> value);
    partial void OnLAST_UPDATED_BY_USER_IDChanged();
    partial void OnCREATED_BY_LOGINChanging(string value);
    partial void OnCREATED_BY_LOGINChanged();
    partial void OnLAST_UPDATED_BY_LOGINChanging(string value);
    partial void OnLAST_UPDATED_BY_LOGINChanged();
    partial void OnOLD_MODULE_IDChanging(System.Nullable<int> value);
    partial void OnOLD_MODULE_IDChanged();
    #endregion
		
		public MODULE()
		{
			this._CHURCH_MODULEs = new EntitySet<CHURCH_MODULE>(new Action<CHURCH_MODULE>(this.attach_CHURCH_MODULEs), new Action<CHURCH_MODULE>(this.detach_CHURCH_MODULEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					this.OnMODULE_IDChanging(value);
					this.SendPropertyChanging();
					this._MODULE_ID = value;
					this.SendPropertyChanged("MODULE_ID");
					this.OnMODULE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_NAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MODULE_NAME
		{
			get
			{
				return this._MODULE_NAME;
			}
			set
			{
				if ((this._MODULE_NAME != value))
				{
					this.OnMODULE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._MODULE_NAME = value;
					this.SendPropertyChanged("MODULE_NAME");
					this.OnMODULE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this.OnCREATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATED_DATE = value;
					this.SendPropertyChanged("CREATED_DATE");
					this.OnCREATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY_USER_ID", DbType="Int")]
		public System.Nullable<int> CREATED_BY_USER_ID
		{
			get
			{
				return this._CREATED_BY_USER_ID;
			}
			set
			{
				if ((this._CREATED_BY_USER_ID != value))
				{
					this.OnCREATED_BY_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._CREATED_BY_USER_ID = value;
					this.SendPropertyChanged("CREATED_BY_USER_ID");
					this.OnCREATED_BY_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LAST_UPDATED_DATE
		{
			get
			{
				return this._LAST_UPDATED_DATE;
			}
			set
			{
				if ((this._LAST_UPDATED_DATE != value))
				{
					this.OnLAST_UPDATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATED_DATE = value;
					this.SendPropertyChanged("LAST_UPDATED_DATE");
					this.OnLAST_UPDATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATED_BY_USER_ID", DbType="Int")]
		public System.Nullable<int> LAST_UPDATED_BY_USER_ID
		{
			get
			{
				return this._LAST_UPDATED_BY_USER_ID;
			}
			set
			{
				if ((this._LAST_UPDATED_BY_USER_ID != value))
				{
					this.OnLAST_UPDATED_BY_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATED_BY_USER_ID = value;
					this.SendPropertyChanged("LAST_UPDATED_BY_USER_ID");
					this.OnLAST_UPDATED_BY_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY_LOGIN", DbType="VarChar(20)")]
		public string CREATED_BY_LOGIN
		{
			get
			{
				return this._CREATED_BY_LOGIN;
			}
			set
			{
				if ((this._CREATED_BY_LOGIN != value))
				{
					this.OnCREATED_BY_LOGINChanging(value);
					this.SendPropertyChanging();
					this._CREATED_BY_LOGIN = value;
					this.SendPropertyChanged("CREATED_BY_LOGIN");
					this.OnCREATED_BY_LOGINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATED_BY_LOGIN", DbType="VarChar(20)")]
		public string LAST_UPDATED_BY_LOGIN
		{
			get
			{
				return this._LAST_UPDATED_BY_LOGIN;
			}
			set
			{
				if ((this._LAST_UPDATED_BY_LOGIN != value))
				{
					this.OnLAST_UPDATED_BY_LOGINChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATED_BY_LOGIN = value;
					this.SendPropertyChanged("LAST_UPDATED_BY_LOGIN");
					this.OnLAST_UPDATED_BY_LOGINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OLD_MODULE_ID", DbType="Int")]
		public System.Nullable<int> OLD_MODULE_ID
		{
			get
			{
				return this._OLD_MODULE_ID;
			}
			set
			{
				if ((this._OLD_MODULE_ID != value))
				{
					this.OnOLD_MODULE_IDChanging(value);
					this.SendPropertyChanging();
					this._OLD_MODULE_ID = value;
					this.SendPropertyChanged("OLD_MODULE_ID");
					this.OnOLD_MODULE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MODULE_CHURCH_MODULE", Storage="_CHURCH_MODULEs", ThisKey="MODULE_ID", OtherKey="MODULE_ID")]
		public EntitySet<CHURCH_MODULE> CHURCH_MODULEs
		{
			get
			{
				return this._CHURCH_MODULEs;
			}
			set
			{
				this._CHURCH_MODULEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHURCH_MODULEs(CHURCH_MODULE entity)
		{
			this.SendPropertyChanging();
			entity.MODULE = this;
		}
		
		private void detach_CHURCH_MODULEs(CHURCH_MODULE entity)
		{
			this.SendPropertyChanging();
			entity.MODULE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ChmPortal.dbo.CHURCH_MODULE")]
	public partial class CHURCH_MODULE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MODULE_ID;
		
		private int _CHURCH_ID;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private System.Nullable<int> _CREATED_BY_USER_ID;
		
		private System.Nullable<System.DateTime> _LAST_UPDATED_DATE;
		
		private System.Nullable<int> _LAST_UPDATED_BY_USER_ID;
		
		private string _CREATED_BY_LOGIN;
		
		private string _LAST_UPDATED_BY_LOGIN;
		
		private EntityRef<MODULE> _MODULE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMODULE_IDChanging(int value);
    partial void OnMODULE_IDChanged();
    partial void OnCHURCH_IDChanging(int value);
    partial void OnCHURCH_IDChanged();
    partial void OnCREATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATED_DATEChanged();
    partial void OnCREATED_BY_USER_IDChanging(System.Nullable<int> value);
    partial void OnCREATED_BY_USER_IDChanged();
    partial void OnLAST_UPDATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnLAST_UPDATED_DATEChanged();
    partial void OnLAST_UPDATED_BY_USER_IDChanging(System.Nullable<int> value);
    partial void OnLAST_UPDATED_BY_USER_IDChanged();
    partial void OnCREATED_BY_LOGINChanging(string value);
    partial void OnCREATED_BY_LOGINChanged();
    partial void OnLAST_UPDATED_BY_LOGINChanging(string value);
    partial void OnLAST_UPDATED_BY_LOGINChanged();
    #endregion
		
		public CHURCH_MODULE()
		{
			this._MODULE = default(EntityRef<MODULE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					if (this._MODULE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMODULE_IDChanging(value);
					this.SendPropertyChanging();
					this._MODULE_ID = value;
					this.SendPropertyChanged("MODULE_ID");
					this.OnMODULE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHURCH_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CHURCH_ID
		{
			get
			{
				return this._CHURCH_ID;
			}
			set
			{
				if ((this._CHURCH_ID != value))
				{
					this.OnCHURCH_IDChanging(value);
					this.SendPropertyChanging();
					this._CHURCH_ID = value;
					this.SendPropertyChanged("CHURCH_ID");
					this.OnCHURCH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this.OnCREATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATED_DATE = value;
					this.SendPropertyChanged("CREATED_DATE");
					this.OnCREATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY_USER_ID", DbType="Int")]
		public System.Nullable<int> CREATED_BY_USER_ID
		{
			get
			{
				return this._CREATED_BY_USER_ID;
			}
			set
			{
				if ((this._CREATED_BY_USER_ID != value))
				{
					this.OnCREATED_BY_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._CREATED_BY_USER_ID = value;
					this.SendPropertyChanged("CREATED_BY_USER_ID");
					this.OnCREATED_BY_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LAST_UPDATED_DATE
		{
			get
			{
				return this._LAST_UPDATED_DATE;
			}
			set
			{
				if ((this._LAST_UPDATED_DATE != value))
				{
					this.OnLAST_UPDATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATED_DATE = value;
					this.SendPropertyChanged("LAST_UPDATED_DATE");
					this.OnLAST_UPDATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATED_BY_USER_ID", DbType="Int")]
		public System.Nullable<int> LAST_UPDATED_BY_USER_ID
		{
			get
			{
				return this._LAST_UPDATED_BY_USER_ID;
			}
			set
			{
				if ((this._LAST_UPDATED_BY_USER_ID != value))
				{
					this.OnLAST_UPDATED_BY_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATED_BY_USER_ID = value;
					this.SendPropertyChanged("LAST_UPDATED_BY_USER_ID");
					this.OnLAST_UPDATED_BY_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY_LOGIN", DbType="VarChar(20)")]
		public string CREATED_BY_LOGIN
		{
			get
			{
				return this._CREATED_BY_LOGIN;
			}
			set
			{
				if ((this._CREATED_BY_LOGIN != value))
				{
					this.OnCREATED_BY_LOGINChanging(value);
					this.SendPropertyChanging();
					this._CREATED_BY_LOGIN = value;
					this.SendPropertyChanged("CREATED_BY_LOGIN");
					this.OnCREATED_BY_LOGINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATED_BY_LOGIN", DbType="VarChar(20)")]
		public string LAST_UPDATED_BY_LOGIN
		{
			get
			{
				return this._LAST_UPDATED_BY_LOGIN;
			}
			set
			{
				if ((this._LAST_UPDATED_BY_LOGIN != value))
				{
					this.OnLAST_UPDATED_BY_LOGINChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATED_BY_LOGIN = value;
					this.SendPropertyChanged("LAST_UPDATED_BY_LOGIN");
					this.OnLAST_UPDATED_BY_LOGINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MODULE_CHURCH_MODULE", Storage="_MODULE", ThisKey="MODULE_ID", OtherKey="MODULE_ID", IsForeignKey=true)]
		public MODULE MODULE
		{
			get
			{
				return this._MODULE.Entity;
			}
			set
			{
				MODULE previousValue = this._MODULE.Entity;
				if (((previousValue != value) 
							|| (this._MODULE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MODULE.Entity = null;
						previousValue.CHURCH_MODULEs.Remove(this);
					}
					this._MODULE.Entity = value;
					if ((value != null))
					{
						value.CHURCH_MODULEs.Add(this);
						this._MODULE_ID = value.MODULE_ID;
					}
					else
					{
						this._MODULE_ID = default(int);
					}
					this.SendPropertyChanged("MODULE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
